version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'teradatalabs/presto-yarn-hdp2.3-master:1'
    ports:
      - '8088:8088'
      - '50070:50070'
    privileged: true

  hadoop-slave1:
    hostname: 'hadoop-slave1'
    image: 'teradatalabs/presto-yarn-hdp2.3-slave:1'
    privileged: true

  hadoop-slave2:
    hostname: 'hadoop-slave2'
    image: 'teradatalabs/presto-yarn-hdp2.3-slave:1'
    privileged: true

  hadoop-slave3:
    hostname: 'hadoop-slave3'
    image: 'teradatalabs/presto-yarn-hdp2.3-slave:1'
    privileged: true

  hadoop-slave4:
    hostname: 'hadoop-slave4'
    image: 'teradatalabs/presto-yarn-hdp2.3-slave:1'
    privileged: true

  runner:
    image: 'teradatalabs/centos6-java8-oracle'
    ports:
      - '5005:5005'
    volumes:
      - '../../..:/workspace'

