cluster:
  master: master
  slaves:
    - slave1
    - slave2
    - slave3

hdfs:
  username: hdfs
  webhdfs:
    host: ${cluster.master}
    port: 50070

databases:
  hive:
    host: ${cluster.master}
    jdbc_driver_class: org.apache.hive.jdbc.HiveDriver
    jdbc_url: jdbc:hive2://${databases.hive.host}:10000
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    table_manager_type: hive

tests:
  hdfs:
    path: /product-test/presto-yarn
  app_package:
    path: target/package
  slider:
    binary: target/package/slider-assembly-0.80.0-incubating-all.zip
    conf_dir: target/package/

ssh:
  identity: ${IDENTITY_FILE}
  roles:
    yarn:
      host: ${cluster.master}
      port: 22
      user: yarn
      password: yarntest
